# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import muscle_manager_protocol_pb2 as muscle__manager__protocol__pb2


class MuscleManagerStub(object):
  """The MUSCLE Manager Protocol
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.SubmitLogMessage = channel.unary_unary(
        '/muscle_manager_protocol.MuscleManager/SubmitLogMessage',
        request_serializer=muscle__manager__protocol__pb2.LogMessage.SerializeToString,
        response_deserializer=muscle__manager__protocol__pb2.LogResult.FromString,
        )


class MuscleManagerServicer(object):
  """The MUSCLE Manager Protocol
  """

  def SubmitLogMessage(self, request, context):
    """Sends a logged message to the Manager
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_MuscleManagerServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'SubmitLogMessage': grpc.unary_unary_rpc_method_handler(
          servicer.SubmitLogMessage,
          request_deserializer=muscle__manager__protocol__pb2.LogMessage.FromString,
          response_serializer=muscle__manager__protocol__pb2.LogResult.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'muscle_manager_protocol.MuscleManager', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
