# ReadTheDocs configuration

version: 2

# Optionally set the version of Python and requirements required to build your docs
python:
  version: 3.6
  install:
    - requirements: docs/requirements.txt
