# ReadTheDocs configuration

version: 2

build:
  os: "ubuntu-20.04"
  tools:
    python: "3.8"
  jobs:
    post_create_environment:
      - pip install tox\<4
      # let tox set up a build environment
      - tox -e docs --notest
      # export tox installed packages as requirements for the install step
      - .tox/docs/bin/pip freeze > docs/requirements.txt
    post_install:
      - pip install -r docs/requirements.txt
