# Run Continuous Integration on every push
name: continuous_integration
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake gfortran libopenmpi-dev pkg-config wget valgrind
        sudo apt-get install -y libssl-dev zlib1g-dev
        pip install tox

    - name: Build and run the test suite
      env:
        MUSCLE_ENABLE_MPI: 1
      run: |
        cd $GITHUB_WORKSPACE
        make test
