# Run Continuous Integration on macOS 13 Ventura, with native Clang and
# without Fortran.

# This mainly checks for issues/regressions in the native build
name: compatibility_macos_ventura_13_clang
on:
  schedule:
    - cron: '30 2 * * 6'
  push:
    branches:
      - 'release-*'
      - fix_native_compatibility_ci
jobs:
  build:
    runs-on: macos-13
    timeout-minutes: 30

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        brew install openmpi
        brew install pkg-config
        python3 -m pip install --upgrade pip
        pip3 install tox tox-gh-actions

    - name: Run all tests on macOS Ventura 13 with Clang
      run: cd ${GITHUB_WORKSPACE} && make test test_examples

