# Run Continuous Integration on macOS 15 Sequoia with GCC
# This includes Fortran support
# This mainly checks for issues/regressions in the native build
name: compatibility_macos_sequoia_15_gcc_gfortran
on:
  schedule:
    - cron: '00 2 * * 6'
  push:
    branches:
      - 'release-*'
      - fix_native_compatibility_ci
jobs:
  build:
    runs-on: macos-15
    timeout-minutes: 30

    steps:
    - uses: actions/checkout@v4

    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest

    - name: Install dependencies
      run: |
        HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK=1 brew install openmpi
        python3 -m venv ${GITHUB_WORKSPACE}/test_venv
        . ${GITHUB_WORKSPACE}/test_venv/bin/activate && pip install tox tox-gh-actions

    - name: Run all tests
      run: cd ${GITHUB_WORKSPACE} && PATH=$PATH:${GITHUB_WORKSPACE}/test_venv/bin CXX=g++-14 OMPI_CXX=g++-14 FC=gfortran-14 OMPI_FC=gfortran-14 make test test_examples
