# Run Continuous Integration when a PR is updated and for pushes to main/develop
name: python_compatibility
on:
  push:
    branches: [main, develop]
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13", "3.14"]

    steps:
    - name: Check out the source code
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Cache Tox
      uses: actions/cache@v3
      with:
        path: ${{ github.workspace }}/.tox
        key: python-compatibility-${{ matrix.python-version }}-tox

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox tox-gh-actions

    - name: Run the test suite
      run: make test_python_only
